import type { Metadata } from "next";
import { IBM_Plex_Mono} from "next/font/google";
import "../styles/main.scss";

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "AnhLs Dev",
  description: "Generated by anhcaols"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plexMono.className}>{children}</body>
    </html>
  );
}
